name: CI - Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    # convert the trx file to markdown
    - name: Install dotnet-trx
      continue-on-error: true
      run: 
        dotnet tool install -g dotnet-trx

    - name: Restore dependencies
      run: dotnet restore
      working-directory: lib

    - name: Build
      run: dotnet build --no-restore
      working-directory: lib

    - name: Run tests
      run: 
        dotnet test --logger trx; trx --output
      working-directory: lib

    # Upload test results as an artifact
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: lib/TestResults/*.trx
      
    - name: Post comment on pull request
      # Add a comment to the pull request with a link to the test results
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Test Results
          The test results can be downloaded [here](${{ steps.upload-test-results.outputs.download-url }}).
