name: CI - Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: lib

    - name: Build
      run: dotnet build --no-restore
      working-directory: lib

    - name: Run tests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=../../library_test_results.trx"
      working-directory: lib

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: lib/tests/library_test_results.trx

    - name: Output test results to GitHub Summary
      run: 
        ls -l
        ls -l lib
        ls -l lib/tests
#cat lib/tests/library_test_results.trx >> $GITHUB_STEP_SUMMARY
      working-directory: lib