name: CI - Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: lib

    - name: Build
      run: dotnet build --no-restore
      working-directory: lib

    - name: Run tests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"
      working-directory: lib

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: lib/test_results.trx

    - name: Output test results to GitHub Summary
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const testResults = fs.readFileSync('lib/test_results.trx', 'utf8');
          github.summary.addRaw(testResults);
          await github.summary.write();