name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: lib

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: lib

      - name: Pack
        run: dotnet pack --configuration Release --output ./nupkgs /p:PackageVersion=${{ github.event.release.tag_name }}
        working-directory: lib

      - name: Add GitHub NuGet source
        run: dotnet nuget add source --username matpadley --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/matpadley/index.json"

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./lib/nupkgs/DartsScorer.Main.${{ github.event.release.tag_name }}.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}